CREATE TABLE Dozenten(
    Namen                VARCHAR(10) NOT NULL PRIMARY KEY
    ,Gesang              VARCHAR(2)
    ,Gitarre             VARCHAR(2)
    ,Klavier             VARCHAR(2)
    ,Keyboard            VARCHAR(2)
    ,Bass                VARCHAR(2)
    ,Geigen              VARCHAR(2)
    ,Trompete            VARCHAR(2)
    ,Saxophone           VARCHAR(2)
    ,Querflöte           VARCHAR(2)
    ,Klarinette          VARCHAR(2)
    ,Ukulele             VARCHAR(2)
    ,Band                VARCHAR(2)
    ,Schlagzeug          VARCHAR(2)
    ,Spalte15			 VARCHAR(2)
    ,Stundensatz_in_EURO INTEGER NOT NULL
    ,Bankverbindung      VARCHAR(30)
);
INSERT INTO Dozenten(Namen,Gesang,Gitarre,Klavier,Keyboard,Bass,Geigen,Trompete,Saxophone,Querflöte,Klarinette,Ukulele,Band,Schlagzeug,Spalte15,Stundensatz_in_EURO,Bankverbindung) VALUES 
('Oliver',NULL,'ok',NULL,NULL,'ok',NULL,NULL,NULL,NULL,NULL,'ok','ok',NULL,NULL,30,NULL),
('Lea',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'OK','OK',NULL,NULL,NULL,NULL,27,NULL),
('Steve','ok',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,18,NULL),
('Fidel','OK',NULL,'OK','OK',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ok',NULL,NULL,50,NULL),
('Steffi','ok',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,30,NULL),
('Lukas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ok',NULL,25,NULL),
('Dirk',NULL,'ok',NULL,NULL,'ok',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,25,NULL),
('Gunnar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ok',NULL,NULL,NULL,NULL,NULL,NULL,30,NULL),
('Mara',NULL,NULL,'ok',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,25,NULL),
('Marc',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ok',NULL,NULL,NULL,NULL,NULL,NULL,28,NULL),
('Max',NULL,NULL,NULL,NULL,NULL,'ok',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,35,NULL),
('Maren',NULL,NULL,NULL,NULL,NULL,'ok',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,30,NULL),
('Hans',NULL,NULL,NULL,NULL,'ok',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,27,NULL),
('Ralf',NULL,'ok',NULL,NULL,'ok',NULL,NULL,NULL,NULL,NULL,'ok',NULL,NULL,NULL,30,NULL),
('Guido',NULL,NULL,NULL,NULL,NULL,NULL,'ok',NULL,NULL,NULL,NULL,NULL,NULL,NULL,35,NULL),
('Bärbel',NULL,NULL,'ok','ok',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,30,NULL),
('Harald',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ok','ok',NULL,NULL,NULL,NULL,35,NULL),
('Julius',NULL,NULL,NULL,NULL,NULL,NULL,'ok',NULL,NULL,NULL,NULL,NULL,NULL,NULL,30,NULL),
('Eva','OK',NULL,'OK',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,28,NULL);